definitions:
  datasets:
    my_ligo_data:
      format: AIRR
      params:
        path: results/dataset1/simulation/my_sim_inst/batch1.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"
  ml_methods:
    my_pwm_model:
      PWM:
        chain: beta
        sequence_type: amino_acid
        region_type: IMGT_JUNCTION
  reports:
    my_KLKmerCompare_report: KLKmerComparison
    my_pwm_report: PWMSummary

instructions:
  my_train_gen_model_inst:
    type: TrainGenModel
    export_combined_dataset: False
    dataset: my_ligo_data
    method: my_pwm_model
    gen_examples_count: 1000
    number_of_processes: 4
    reports:
      - my_KLKmerCompare_report
      - my_pwm_report