definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: data.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"
  ml_methods:
    my_sonia_model:
      SONIA:
        batch_size: 10000
        epochs: 30 #50
        default_model_name: 'humanIGH' #'humanTRB'
        include_joint_genes: True
        n_gen_seqs: 50000
  reports:
    my_KLKmerCompare_report: KLKmerComparison

instructions:
  gen_model:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: my_sonia_model
    gen_examples_count: 10000
    number_of_processes: 4
    reports:
      - my_KLKmerCompare_report