definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: data/SLG_dataset_output/my_sim_inst/batch1.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"
  ml_methods:
    my_sonnia_model:
      SoNNia:
        batch_size: 10000
        epochs: 50 #50
        default_model_name: 'humanTRB'
        deep: False # this param has no function?
        include_joint_genes: True
        n_gen_seqs: 10000 #500000
  reports:
    my_KLKmerCompare_report: KLKmerComparison

instructions:
  gen_model:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: my_sonnia_model
    gen_examples_count: 1000
    number_of_processes: 4
    reports:
      - my_KLKmerCompare_report