definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: results/dataset1/simulation/my_sim_inst/batch1.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
  ml_methods:
    my_vae_model:
      SimpleVAE:
        chain: beta
        beta: 0.75
        latent_dim: 20
        linear_nodes_count: 75
        num_epochs: 2 #5000
        batch_size: 10000
        j_gene_embed_dim: 13
        v_gene_embed_dim: 30
        cdr3_embed_dim: 21
        pretrains: 10
        warmup_epochs: 20
        patience: 20
        device: cpu

  reports:
    my_KLKmerCompare_report: KLKmerComparison
    my_vae_report:
      VAESummary:
        dim_dist_cols: 4
        dim_dist_rows: None

instructions:
  gen_model:
    type: TrainGenModel
    export_combined_dataset: False
    dataset: dataset
    method: my_vae_model
    gen_examples_count: 1000
    number_of_processes: 4
    reports:
      - my_KLKmerCompare_report
      - my_vae_report
