definitions:
  datasets:
    my_dataset:
      format: AIRR
      params:
        path: results/dataset1/simulation/my_sim_inst/batch1.tsv #results/dataset1/models/VAE/my_train_gen_model_inst/generated_sequences/batch1.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"

  reports:
    my_sld_report: SequenceLengthDistribution
    my_aa_freq_report: AminoAcidFrequencyDistribution

instructions:
  my_instruction:
    type: ExploratoryAnalysis
    analyses:
      SeqLen:
        dataset: my_dataset
        report: my_sld_report
      AA:
        dataset: my_dataset
        report: my_aa_freq_report