definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: data.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"

  reports:
    my_sld_report:
      SequenceLengthDistribution:
        region_type: IMGT_JUNCTION
    my_aa_freq_report: AminoAcidFrequencyDistribution

instructions:
  report_types:
    type: ExploratoryAnalysis
    analyses:
      SeqLen:
        dataset: dataset
        report: my_sld_report
      AA:
        dataset: dataset
        report: my_aa_freq_report