n_experiments: 5
output_dir: "results/phenotype_simulated/experiment"
data_processing:
  simulation:
    method: "rare_and_frequent"
    n_samples: 5
    model: "humanTRB"
    seed: 42
models:
  sonia:
    config: "../../../configs/generative_models/SONIA.yaml"
  pwm:
    config: "../../../configs/generative_models/PWM.yaml"
