n_experiments: 2
output_dir: "../../../results/phenotype_simulated"
seed: 42
simulation:
  method: "rare_and_frequent"
  n_samples: 5
  model: "humanTRB"
models:
    - name: "pwm"
      config: "../../../configs/generative_models/PWM.yaml"
    - name: "sonia"
      config: "../../../configs/generative_models/SONIA.yaml"
analyses:
    - name: "phenotype"
      model: "pwm"
    - name: "phenotype"
      model: "sonia"
