n_experiments: 5
output_dir: "results/phenotype_simulated"
data_processing:
  simulation:
    method: "rare_and_frequent"
    n_samples: 25000
    model: "humanTRB"
    seed: 42
models:
    - name: "sonia"
      config: "../../../configs/generative_models/SONIA.yaml"
    - name: "pwm"
      config: "../../../configs/generative_models/PWM.yaml"
analyses:
    - name: "phenotype"
      model: "sonia"
    - name: "phenotype"
      model: "pwm"
