n_experiments: 2
output_dir: "results2/phenotype_simulated"
input_dir: "data"
seed: 42
data_generation:
  experimental: False
  method: "rare_and_frequent"
  n_samples: 10
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call"]
models:
    - name: "pwm"
      config: "configs/generative_models/PWM.yaml"
      train_dir: ""
    - name: "sonia"
      config: "configs/generative_models/SONIA.yaml"
      train_dir: ""
analyses:
    - name: "phenotype"
      model_names: ["pwm"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["sonia"]
      default_model_name: "humanTRB"
